spring:
  application:
    name: flowcrm
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/flowcrm-db}
    username: ${DB_USER:rakshit}
    password: ${DB_PASS:password}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:29092}
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        retries: 3
        spring.json.add.type.headers: false
    consumer:
      group-id: flowcrm-monolith
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.flowcrm.*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.flowcrm.kafka.dto.EventEnvelope

jwt:
  secret-key: dont-use-in-prod-a9asd7fulasjdfaklsdfu98q3uhjdiosh897as9d8f7ua9osufdjilasdjf
  access-token-expiration-ms: 86400000 # 24 hours in ms
  refresh-token-expiration-ms: 604800000 # 7 days in ms

app:
  rate-limit:
    method: fixed
    use-case:
      api-key:
        requests-per-minute: 2
  kafka:
    topics:
      lead: leads.events
      task: tasks.events

outbox:
  polling:
    fixed-delay: 5000
  retry:
    max-attempts: 3

kafka:
  consumer:
    retry:
      max-attempts: 3


